import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {readStore,updateStore} from "@/lib/storage/db";
import type {Contact} from "@/types";

const phoneSchema=z.string().trim().regex(/^\+?[\d\s().-]{10,20}$/,"Informe um WhatsApp válido.");
const createSchema=z.object({name:z.string().trim().min(1).max(120),phone:phoneSchema,company:z.string().max(160).default(""),email:z.string().email().or(z.literal("")).default(""),city:z.string().max(120).default(""),segment:z.string().max(100).default(""),notes:z.string().max(2000).optional().default(""),tags:z.array(z.string().max(40)).default([]),status:z.enum(["Novo","Contatado","Respondeu","Interessado","Proposta","Negociação","Cliente","Sem interesse"]).default("Novo"),optedIn:z.boolean().default(false),optedOut:z.boolean().default(false)});
const normalize=(value:string)=>value.replace(/\D/g,"");
export async function GET(req:NextRequest){const store=await readStore();const q=(req.nextUrl.searchParams.get("q")||"").toLocaleLowerCase("pt-BR");const status=req.nextUrl.searchParams.get("status");return NextResponse.json(store.contacts.filter(c=>(!q||[c.name,c.phone,c.company,c.city,c.segment,...c.tags].join(" ").toLocaleLowerCase("pt-BR").includes(q))&&(!status||status==="Todos os status"||(status==="Bloqueados"?c.optedOut:c.status===status))))}
export async function POST(req:NextRequest){try{const body=createSchema.parse(await req.json());const contact=await updateStore(store=>{if(store.contacts.some(c=>normalize(c.phone)===normalize(body.phone)))throw new Error("Já existe um contato com esse WhatsApp.");const row:Contact={...body,id:crypto.randomUUID(),lastContact:"—"};store.contacts.unshift(row);return row});return NextResponse.json(contact,{status:201})}catch(error){return NextResponse.json({error:error instanceof z.ZodError?error.issues[0]?.message:error instanceof Error?error.message:"Não foi possível criar o contato."},{status:400})}}
export async function PATCH(req:NextRequest){try{const body=z.object({id:z.string().min(1),changes:createSchema.partial()}).parse(await req.json());const contact=await updateStore(store=>{const row=store.contacts.find(c=>c.id===body.id);if(!row)throw new Error("Contato não encontrado.");if(body.changes.phone&&store.contacts.some(c=>c.id!==row.id&&normalize(c.phone)===normalize(body.changes.phone!)))throw new Error("Já existe um contato com esse WhatsApp.");Object.assign(row,body.changes);return row});return NextResponse.json(contact)}catch(error){return NextResponse.json({error:error instanceof z.ZodError?error.issues[0]?.message:error instanceof Error?error.message:"Não foi possível atualizar o contato."},{status:400})}}
export async function PUT(req:NextRequest){try{const{contacts}=z.object({contacts:z.array(createSchema.extend({id:z.string().min(1),lastContact:z.string().default("—")})).max(10000)}).parse(await req.json());const result=await updateStore(store=>{const seen=new Set<string>();for(const contact of contacts){const phone=normalize(contact.phone);if(seen.has(phone))throw new Error("A lista contém WhatsApps duplicados.");seen.add(phone)}store.contacts=contacts as Contact[];return store.contacts.length});return NextResponse.json({saved:result})}catch(error){return NextResponse.json({error:error instanceof z.ZodError?error.issues[0]?.message:error instanceof Error?error.message:"Não foi possível salvar contatos."},{status:400})}}
export async function DELETE(req:NextRequest){try{const{ids}=z.object({ids:z.array(z.string()).min(1)}).parse(await req.json());const removed=await updateStore(store=>{const before=store.contacts.length;store.contacts=store.contacts.filter(c=>!ids.includes(c.id));const deleted=new Set(ids);store.jobs=store.jobs.map(job=>deleted.has(job.contactId)&&job.status==="pending"?{...job,status:"skipped"}:job);return before-store.contacts.length});return NextResponse.json({deleted:removed})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Não foi possível excluir contatos."},{status:400})}}
