import {mkdir,readFile,rename,rm,stat,writeFile} from "node:fs/promises";
import path from "node:path";
import {randomUUID} from "node:crypto";
import {initialCampaigns,initialContacts} from "@/lib/data";
import type {Campaign,CampaignMessageJob,Contact,ContactList,Message,MessageTemplate} from "@/types";
import {createSubscription,normalizeSubscription,type SubscriptionRecord} from "@/lib/billing/plans";

export interface CampaignRecord extends Campaign {message:string;contactIds:string[];instanceName:string;minIntervalSeconds:number;dailyLimit:number;startTime:string;endTime:string;weekdays:number[];pauseOnReply:boolean;scheduledAt?:string}
export interface StoredMessage extends Message {number?:string}
export interface StoredCampaignJob extends CampaignMessageJob {text:string;instanceName:string}
export interface AppUser {id:string;name:string;email:string;passwordHash:string;passwordSalt:string;role:"admin"|"user";status:"active"|"disabled";createdAt:string;lastLoginAt?:string}
export interface AppSession {id:string;userId:string;expiresAt:string}
export interface FlowSendStore {contacts:Contact[];campaigns:CampaignRecord[];messages:StoredMessage[];jobs:StoredCampaignJob[];instances:import("@/types").WhatsAppInstance[];subscription:SubscriptionRecord;lists:ContactList[];templates:MessageTemplate[];settings:{workspaceName:string;email:string;timezone:string;optOutPolicy:string};users:AppUser[];sessions:AppSession[]}

const dataDirectory=()=>process.env.FLOWSEND_DATA_DIR||path.join(process.cwd(),".data");
const filePath=()=>path.join(dataDirectory(),"flowsend.json");
const lockPath=()=>`${filePath()}.lock`;
const seed=():FlowSendStore=>({contacts:initialContacts,campaigns:initialCampaigns.map(c=>({...c,message:"",contactIds:[],instanceName:process.env.EVOLUTION_INSTANCE_NAME||"flowsend-comercial",minIntervalSeconds:30,dailyLimit:250,startTime:"09:00",endTime:"18:00",weekdays:[1,2,3,4,5],pauseOnReply:false})),messages:[{id:"demo-m1",contactId:"c1",direction:"out",text:"Olá, Mariana! Tudo bem? Posso te apresentar como ajudamos clínicas a organizar o relacionamento com pacientes?",time:new Date(Date.now()-18*60_000).toISOString(),status:"demonstration"},{id:"demo-m2",contactId:"c1",direction:"in",text:"Oi! Tenho interesse! Pode me contar mais?",time:new Date(Date.now()-12*60_000).toISOString(),status:"demonstration"},{id:"demo-m3",contactId:"c2",direction:"out",text:"Olá, Rafael! Conheça nossa plataforma de relacionamento.",time:new Date(Date.now()-52*60_000).toISOString(),status:"demonstration"},{id:"demo-m4",contactId:"c2",direction:"in",text:"Legal! Como funciona?",time:new Date(Date.now()-44*60_000).toISOString(),status:"demonstration"}],jobs:[],instances:[],subscription:createSubscription(),lists:[{id:"list-clinicas",name:"Clínicas",tag:"Clínicas",createdAt:new Date().toISOString()},{id:"list-restaurantes",name:"Restaurantes",tag:"Restaurantes",createdAt:new Date().toISOString()},{id:"list-hoteis",name:"Hotéis",tag:"Hotéis",createdAt:new Date().toISOString()},{id:"list-leads",name:"Leads novos",tag:"Lead novo",createdAt:new Date().toISOString()}],templates:[{id:"tpl-prospeccao",name:"Primeiro contato",category:"Prospecção",text:"Olá, {{nome}}! Tudo bem? Acredito que podemos ajudar a {{empresa}}.",favorite:false,createdAt:new Date().toISOString()},{id:"tpl-followup",name:"Retomar conversa",category:"Follow-up",text:"Oi, {{nome}}! Passando para saber se conseguiu avaliar nossa proposta.",favorite:false,createdAt:new Date().toISOString()},{id:"tpl-posvenda",name:"Boas-vindas",category:"Pós-venda",text:"Olá, {{nome}}! Obrigado por escolher a gente. Estamos à disposição!",favorite:false,createdAt:new Date().toISOString()}],settings:{workspaceName:"Acme Studio",email:"gabriel@acmestudio.com.br",timezone:"America/Sao_Paulo",optOutPolicy:"Bloquear novos envios automaticamente"},users:[],sessions:[]});

async function ensureStore(){await mkdir(dataDirectory(),{recursive:true});try{await readFile(filePath(),"utf8")}catch{try{await writeFile(filePath(),JSON.stringify(seed(),null,2),{encoding:"utf8",flag:"wx"})}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error}}}
async function readUnlocked(){await ensureStore();const saved=JSON.parse(await readFile(filePath(),"utf8")) as Partial<FlowSendStore>;const defaults=seed();return {...defaults,...saved,contacts:saved.contacts??defaults.contacts,campaigns:saved.campaigns??defaults.campaigns,messages:saved.messages??defaults.messages,jobs:saved.jobs??defaults.jobs,instances:saved.instances??defaults.instances,subscription:normalizeSubscription(saved.subscription),lists:saved.lists??defaults.lists,templates:saved.templates??defaults.templates,settings:saved.settings??defaults.settings,users:saved.users??defaults.users,sessions:saved.sessions??defaults.sessions} as FlowSendStore}
async function acquireLock(){await ensureStore();for(let i=0;i<200;i++){try{await mkdir(lockPath());return async()=>rm(lockPath(),{recursive:true,force:true})}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;try{const info=await stat(lockPath());if(Date.now()-info.mtimeMs>60_000)await rm(lockPath(),{recursive:true,force:true})}catch{}await new Promise(resolve=>setTimeout(resolve,25))}}throw new Error("O armazenamento está ocupado. Tente novamente.")}
export async function readStore(){return readUnlocked()}
export async function updateStore<T>(update:(store:FlowSendStore)=>T|Promise<T>):Promise<T>{const release=await acquireLock();try{const store=await readUnlocked();const result=await update(store);const temp=`${filePath()}.${process.pid}.${randomUUID()}.tmp`;await writeFile(temp,JSON.stringify(store,null,2),"utf8");await rename(temp,filePath());return result}finally{await release()}}
