"use client";
import { useEffect, useState } from "react";
import { BellRing, Check, LockKeyhole, Save, Shield, UserRound } from "lucide-react";

type Settings = { workspaceName: string; email: string; timezone: string; optOutPolicy: string; reportSchedule: { enabled: boolean; frequency: "daily" | "weekly" | "monthly"; phone: string; instanceName: string; lastSentPeriod?: string } };
const initial: Settings = { workspaceName: "", email: "", timezone: "America/Sao_Paulo", optOutPolicy: "Bloquear novos envios automaticamente", reportSchedule: { enabled: false, frequency: "weekly", phone: "", instanceName: "flowsend-comercial" } };
const tabs = ["Empresa", "Preferências", "Segurança"] as const;
export default function SettingsPage() {
  const [form, setForm] = useState<Settings>(initial); const [tab, setTab] = useState<(typeof tabs)[number]>("Empresa"); const [saved, setSaved] = useState(false); const [error, setError] = useState(""); const [password, setPassword] = useState({ currentPassword: "", newPassword: "", confirm: "" });
  useEffect(() => { fetch("/api/settings").then(async (response) => { if (!response.ok) throw new Error(); const data = await response.json(); setForm({ ...initial, ...data, reportSchedule: { ...initial.reportSchedule, ...data.reportSchedule } }); }).catch(() => setError("Não foi possível carregar as configurações.")); }, []);
  async function save() { setError(""); const response = await fetch("/api/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Não foi possível salvar."); return; } setForm(data); setSaved(true); setTimeout(() => setSaved(false), 2500); }
  async function changePassword(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); if (password.newPassword !== password.confirm) { setError("As senhas novas não conferem."); return; } const response = await fetch("/api/auth/password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword: password.currentPassword, newPassword: password.newPassword }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Não foi possível alterar a senha."); return; } setPassword({ currentPassword: "", newPassword: "", confirm: "" }); setError("Senha alterada com sucesso."); }
  return <><div className="page-heading"><div><h1>Configurações</h1><p>Gerencie os dados, preferências e segurança do workspace.</p></div></div><nav className="settings-tabs">{tabs.map((item) => <button className={tab === item ? "active" : ""} key={item} onClick={() => setTab(item)}>{item}</button>)}</nav>
    {tab === "Empresa" && <section className="integration-card"><div className="integration-head"><span className="integration-logo"><UserRound size={20}/></span><div><h2>Dados cadastrais</h2><p>Perfil e contato da empresa</p></div></div><div className="integration-fields" style={{ marginTop: 16 }}><div className="form-field"><label>Nome do workspace</label><input value={form.workspaceName} onChange={(event) => setForm({ ...form, workspaceName: event.target.value })}/></div><div className="form-field"><label>Email de contato</label><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })}/></div></div><div className="integration-foot"><span className="help-text">Dados salvos no workspace.</span><button className="btn btn-primary" onClick={save}>{saved ? <Check size={14}/> : <Save size={14}/>} {saved ? "Salvo" : "Salvar alterações"}</button></div></section>}
    {tab === "Preferências" && <section className="integration-card"><div className="integration-head"><span className="integration-logo"><BellRing size={20}/></span><div><h2>Preferências do sistema</h2><p>Fuso horário, opt-out e resumo automático pelo WhatsApp</p></div></div><div className="integration-fields" style={{ marginTop: 16 }}><div className="form-field"><label>Fuso horário</label><select value={form.timezone} onChange={(event) => setForm({ ...form, timezone: event.target.value })}><option value="America/Sao_Paulo">America/Sao_Paulo (GMT-3)</option><option value="UTC">UTC</option></select></div><div className="form-field"><label>Política de opt-out</label><select value={form.optOutPolicy} onChange={(event) => setForm({ ...form, optOutPolicy: event.target.value })}><option>Bloquear novos envios automaticamente</option></select></div><label className="legal-check full"><input type="checkbox" checked={form.reportSchedule.enabled} onChange={(event) => setForm({ ...form, reportSchedule: { ...form.reportSchedule, enabled: event.target.checked } })}/> Enviar resumo automático de relatórios pelo WhatsApp</label><div className="form-field"><label>Frequência</label><select value={form.reportSchedule.frequency} onChange={(event) => setForm({ ...form, reportSchedule: { ...form.reportSchedule, frequency: event.target.value as Settings["reportSchedule"]["frequency"] } })}><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option></select></div><div className="form-field"><label>Instância Evolution</label><input value={form.reportSchedule.instanceName} onChange={(event) => setForm({ ...form, reportSchedule: { ...form.reportSchedule, instanceName: event.target.value } })}/></div><div className="form-field full"><label>WhatsApp destinatário com código do país</label><input value={form.reportSchedule.phone} onChange={(event) => setForm({ ...form, reportSchedule: { ...form.reportSchedule, phone: event.target.value } })} placeholder="+55 11 99999-9999"/></div></div><div className="warning-box">O resumo é enviado pelo worker quando estiver ativo. A frequência define a janela do relatório; mantenha a instância Evolution conectada.</div><div className="integration-foot"><span className="help-text">Os relatórios automáticos incluem contagens e não incluem PDF.</span><button className="btn btn-primary" onClick={save}>{saved ? <Check size={14}/> : <Save size={14}/>} {saved ? "Salvo" : "Salvar preferências"}</button></div></section>}
    {tab === "Segurança" && <form className="integration-card" onSubmit={changePassword}><div className="integration-head"><span className="integration-logo"><LockKeyhole size={20}/></span><div><h2>Alterar senha</h2><p>Use uma senha com pelo menos 10 caracteres.</p></div></div><div className="integration-fields" style={{ marginTop: 16 }}><div className="form-field full"><label>Senha atual</label><input required type="password" autoComplete="current-password" value={password.currentPassword} onChange={(event) => setPassword({ ...password, currentPassword: event.target.value })}/></div><div className="form-field"><label>Nova senha</label><input required minLength={10} type="password" autoComplete="new-password" value={password.newPassword} onChange={(event) => setPassword({ ...password, newPassword: event.target.value })}/></div><div className="form-field"><label>Confirmar senha</label><input required minLength={10} type="password" autoComplete="new-password" value={password.confirm} onChange={(event) => setPassword({ ...password, confirm: event.target.value })}/></div></div><div className="integration-foot"><span className="help-text"><Shield size={13}/> A senha é armazenada com hash seguro.</span><button className="btn btn-primary"><LockKeyhole size={14}/> Atualizar senha</button></div></form>}
    {error && <div className="connection-state">{error}</div>}</>;
}
