"use client";
import {useEffect,useMemo,useState} from "react";
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {Download} from "lucide-react";
import Link from "next/link";
import type {Campaign,Contact,Message} from "@/types";

export default function Reports(){
 const[period,setPeriod]=useState(30);const[now,setNow]=useState(0);const[campaigns,setCampaigns]=useState<Campaign[]>([]);const[contacts,setContacts]=useState<Contact[]>([]);const[messages,setMessages]=useState<Message[]>([]);
 useEffect(()=>{Promise.all([fetch("/api/campaigns").then(r=>r.json()),fetch("/api/contacts").then(r=>r.json()),fetch("/api/messages").then(r=>r.json())]).then(([campaignRows,contactRows,messageRows])=>{setCampaigns(campaignRows);setContacts(contactRows);setMessages(messageRows);setNow(Date.now())}).catch(()=>{})},[]);
 const cutoff=now-period*86400000;
 const relevant=useMemo(()=>messages.filter(message=>Date.parse(message.time)>=cutoff&&message.status!=="demonstration"),[messages,cutoff]);
 const sent=relevant.filter(message=>message.direction==="out");const received=relevant.filter(message=>message.direction==="in");
 const delivered=sent.filter(message=>["delivered","read"].includes(message.status)).length;const read=sent.filter(message=>message.status==="read").length;
 const interested=contacts.filter(contact=>contact.status==="Interessado").length;const opportunities=contacts.filter(contact=>["Proposta","Negociação"].includes(contact.status)).length;const sales=contacts.filter(contact=>contact.status==="Cliente").length;
 const data=useMemo(()=>{const count=period===7?7:30;const start=now-period*86400000;const step=(period*86400000)/count;const points=Array.from({length:count},(_,index)=>{const date=new Date(start+(index+.5)*step);return{key:date.toDateString(),label:new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short"}).format(date),sent:0,replies:0}});for(const message of relevant){const index=Math.floor((Date.parse(message.time)-start)/step);if(index>=0&&index<points.length){if(message.direction==="out")points[index].sent++;else points[index].replies++}}return points},[period,now,relevant]);
 function exportCsv(){const rows:[string,string|number][]=[["Indicador","Valor"],["Mensagens enviadas",sent.length],["Entregues",delivered],["Lidas",read],["Respostas",received.length],["Interessados",interested],["Oportunidades",opportunities],["Vendas",sales],...campaigns.map(c=>[c.name,c.sent] as [string,number])];const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([rows.map(row=>row.join(",")).join("\n")],{type:"text/csv"}));link.download="flowsend-relatorio.csv";link.click();URL.revokeObjectURL(link.href)}
 const metrics:[string,number][]=[["Mensagens enviadas",sent.length],["Entregues",delivered],["Lidas",read],["Respostas",received.length],["Interessados",interested],["Oportunidades",opportunities],["Vendas",sales]];
 return <><div className="page-heading"><div><div className="eyebrow">DESEMPENHO COMERCIAL</div><h1>Relatórios</h1><p>Resultados calculados a partir das mensagens e contatos armazenados.</p></div><div className="heading-actions"><select className="filter-btn" value={period} onChange={e=>setPeriod(Number(e.target.value))}><option value={7}>Últimos 7 dias</option><option value={30}>Últimos 30 dias</option><option value={90}>Últimos 90 dias</option></select><Link className="btn btn-outline" href="/configuracoes">Agendar resumo no WhatsApp</Link><button className="btn btn-outline" onClick={exportCsv}><Download size={14}/> Exportar</button></div></div><div className="soft-card-grid">{metrics.map(([label,value])=><div className="soft-card" key={label}><p>{label}</p><div className="soft-number">{value.toLocaleString("pt-BR")}</div></div>)}</div><section className="panel" style={{marginTop:15,height:330}}><div className="panel-head"><div><h2>Envios e respostas</h2><p>Mensagens no período selecionado</p></div></div><div style={{height:250,marginTop:18}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><CartesianGrid stroke="#27272a" vertical={false}/><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{fill:"#a1a1aa"}}/><YAxis tickLine={false} axisLine={false} tick={{fill:"#71717a"}}/><Tooltip contentStyle={{background:"#17171c",border:"1px solid rgba(255,255,255,.1)",borderRadius:10,color:"#f4f4f5"}}/><Area dataKey="sent" name="Enviadas" stroke="#818cf8" fill="#818cf822"/><Area dataKey="replies" name="Respostas" stroke="#34d399" fill="#34d39920"/></AreaChart></ResponsiveContainer></div></section></>;
}
