"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {LockKeyhole,LogIn,ShieldCheck} from "lucide-react";

export default function LoginPage(){
 const router=useRouter();const[setupRequired,setSetupRequired]=useState(false);const[ready,setReady]=useState(false);const[name,setName]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/auth/status").then(response=>response.json()).then(data=>setSetupRequired(Boolean(data.setupRequired))).catch(()=>setError("Não foi possível verificar o estado do acesso.")).finally(()=>setReady(true))},[]);
 async function submit(event:FormEvent){event.preventDefault();setError("");if(setupRequired&&password!==confirm){setError("As senhas não coincidem.");return}setBusy(true);try{const response=await fetch(setupRequired?"/api/auth/setup":"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(setupRequired?{name,email,password}:{email,password})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível entrar.");const requested=new URLSearchParams(window.location.search).get("next");const destination=requested&&requested.startsWith("/")&&!requested.startsWith("//")?requested:"/";router.replace(destination);router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Falha no acesso.")}finally{setBusy(false)}}
 return <main className="auth-screen"><section className="auth-card"><div className="auth-brand"><span className="brand-mark">F</span><span>flow<span className="brand-light">send</span><small>SALES PLATFORM</small></span></div><div className="eyebrow">{setupRequired?"CONFIGURAÇÃO INICIAL":"ACESSO AO WORKSPACE"}</div><h1>{setupRequired?"Crie a conta administradora":"Bem-vindo de volta"}</h1><p>{setupRequired?"Esta primeira conta terá acesso de administrador e poderá cadastrar os outros usuários.":"Entre com seu e-mail e senha para continuar."}</p>{!ready?<div className="connection-state">Verificando configuração...</div>:<form onSubmit={submit} className="auth-form">{setupRequired&&<div className="form-field"><label htmlFor="auth-name">Nome completo</label><input id="auth-name" autoComplete="name" required minLength={2} value={name} onChange={event=>setName(event.target.value)}/></div>}<div className="form-field"><label htmlFor="auth-email">E-mail</label><input id="auth-email" type="email" autoComplete="username" required value={email} onChange={event=>setEmail(event.target.value)}/></div><div className="form-field"><label htmlFor="auth-password">{setupRequired?"Crie uma senha (mínimo 10 caracteres)":"Senha"}</label><input id="auth-password" type="password" autoComplete={setupRequired?"new-password":"current-password"} required minLength={setupRequired?10:1} value={password} onChange={event=>setPassword(event.target.value)}/></div>{setupRequired&&<div className="form-field"><label htmlFor="auth-confirm">Confirme a senha</label><input id="auth-confirm" type="password" autoComplete="new-password" required minLength={10} value={confirm} onChange={event=>setConfirm(event.target.value)}/></div>}{error&&<div className="auth-error" role="alert">{error}</div>}<button className="btn btn-primary auth-submit" disabled={busy||!ready}>{setupRequired?<ShieldCheck size={16}/>:<LogIn size={16}/>} {busy?"Aguarde...":setupRequired?"Criar administrador":"Entrar"}</button></form>}<div className="auth-security"><LockKeyhole size={14}/> Senhas protegidas e sessão privada neste navegador.</div></section></main>;
}
