"use client";
import {useCallback,useEffect,useState} from "react";
import {MoreHorizontal,Plus,MessageCircle,X,Phone,Mail,MapPin} from "lucide-react";
import {initialContacts} from "@/lib/data";
import type {Contact,ContactStatus,Message} from "@/types";
const columns:ContactStatus[][]=[["Novo"],["Contatado"],["Respondeu"],["Interessado"],["Proposta"],["Negociação"],["Cliente"],["Sem interesse"]];
const names=["NOVO","CONTATADO","RESPONDEU","INTERESSADO","PROPOSTA","NEGOCIAÇÃO","CLIENTE","SEM INTERESSE"];
export default function CRM(){
 const[contacts,setContacts]=useState<Contact[]>(initialContacts);const[drag,setDrag]=useState<string|null>(null);const[selected,setSelected]=useState<Contact|null>(null);const[timeline,setTimeline]=useState<Message[]>([]);const[toast,setToast]=useState("");
 useEffect(()=>{fetch("/api/contacts").then(r=>r.json()).then((rows:Contact[])=>setContacts(rows)).catch(()=>setToast("Não foi possível carregar contatos."))},[]);
 const loadTimeline=useCallback(async(id:string)=>{const response=await fetch(`/api/messages?contactId=${encodeURIComponent(id)}`);if(response.ok)setTimeline(await response.json())},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(selected)loadTimeline(selected.id).catch(()=>setTimeline([]))},[selected,loadTimeline]);
 async function move(id:string,status:ContactStatus){const response=await fetch("/api/contacts",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,changes:{status}})});const data=await response.json();if(!response.ok){setToast(data.error||"Não foi possível mover o lead.");return}setContacts(rows=>rows.map(row=>row.id===id?data:row));}
 async function addLead(){const name=prompt("Nome do lead");if(!name?.trim())return;const phone=prompt("WhatsApp com código do país");if(!phone?.trim())return;const response=await fetch("/api/contacts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name.trim(),phone:phone.trim()})});const data=await response.json();if(!response.ok){setToast(data.error||"Não foi possível criar lead.");return}setContacts(rows=>[data,...rows]);}
 return <><div className="page-heading"><div><div className="eyebrow">PIPELINE DE VENDAS</div><h1>CRM</h1><p>Acompanhe cada oportunidade da primeira conversa à venda.</p></div><button className="btn btn-primary" onClick={addLead}><Plus size={15}/> Nova oportunidade</button></div><div className="overview-strip"><div className="live-chip">Pipeline ativo</div><span>{contacts.length} contatos no CRM</span><span style={{marginLeft:"auto"}}>Arraste um lead para atualizar o estágio</span></div><div className="kanban">{columns.map((statuses,i)=>{const rows=contacts.filter(c=>statuses.includes(c.status));return <section className="kanban-col" key={names[i]} onDragOver={e=>e.preventDefault()} onDrop={()=>drag&&move(drag,statuses[0])}><div className="kanban-title">{names[i]} <span>{rows.length}</span></div>{rows.map(c=><article className="lead-card" key={c.id} draggable onDragStart={()=>setDrag(c.id)} onClick={()=>{setTimeline([]);setSelected(c)}}><div style={{display:"flex",justifyContent:"space-between"}}><b>{c.name}</b><button className="icon-button" onClick={e=>{e.stopPropagation();setTimeline([]);setSelected(c)}} aria-label="Detalhes do lead"><MoreHorizontal size={15}/></button></div><small>{c.company||c.phone}</small><div className="lead-card-bottom"><span><MessageCircle size={12}/> {c.lastContact}</span><span>{c.tags[0]||"Lead"}</span></div></article>)}</section>})}</div>{toast&&<div className="connection-state">{toast}</div>}{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}><X size={17}/></button><div className="eyebrow">DETALHES DO LEAD</div><h2>{selected.name}</h2><p>{selected.company||"Sem empresa"} · {selected.status}</p><div className="soft-card-grid" style={{gridTemplateColumns:"1fr 1fr"}}><div className="soft-card"><p><Phone size={13}/> WhatsApp</p><b>{selected.phone}</b></div><div className="soft-card"><p><Mail size={13}/> Email</p><b>{selected.email||"—"}</b></div><div className="soft-card"><p><MapPin size={13}/> Cidade / Segmento</p><b>{selected.city||"—"} · {selected.segment||"—"}</b></div><div className="soft-card"><p>Tags</p><b>{selected.tags.join(", ")||"—"}</b></div></div><h3 style={{fontSize:12,marginTop:18}}>Timeline de mensagens</h3><div style={{maxHeight:200,overflow:"auto"}}>{timeline.length?timeline.map(message=><div className="activity-item" key={message.id}><span className={`activity-avatar ${message.direction==="in"?"av-blue":"av-green"}`}><MessageCircle size={14}/></span><div><p>{message.direction==="in"?"Mensagem recebida":"Mensagem enviada"} · {message.status}</p><small>{message.text}</small></div></div>):<p className="empty-note">Ainda não há mensagens registradas.</p>}</div><div className="modal-actions"><button className="btn btn-outline" onClick={()=>setSelected(null)}>Fechar</button><a className="btn btn-primary" href="/mensagens">Abrir conversa</a></div></div></div>}</>;
}
