"use client";
import {useEffect,useState} from "react";
import {usePathname,useRouter} from "next/navigation";
import Link from "next/link";
import {Bell,Search,Command,Menu,LogOut,Crown,ArrowLeft,ArrowRight,Check,ShieldCheck,Sparkles} from "lucide-react";
import {Sidebar} from "./sidebar";
import {UpgradeModal} from "@/components/billing/upgrade-modal";
import type {PlanId} from "@/lib/billing/plans";

type Account={id:string;name:string;email:string;role:"admin"|"user"};
type Billing={plan:PlanId;planName:string;maxMessages:number;maxProspects:number;messagesUsed:number;prospectsUsed:number;whatsappUsed:number;maxWhatsapp:number};
const titles:Record<string,string>={"/":"Visão geral","/contatos":"Contatos","/campanhas":"Campanhas","/crm":"CRM","/mensagens":"Mensagens","/integracoes":"Integrações","/listas":"Listas","/templates":"Templates","/agendamentos":"Agendamentos","/relatorios":"Relatórios","/configuracoes":"Configurações","/usuarios":"Usuários","/planos":"Planos e preços","/pagamentos":"Pagamentos","/ajuda":"Central de ajuda"};
const tourSteps=[{title:"Conheça seu painel",body:"Acompanhe o resumo da operação, campanhas recentes e atividade do workspace no Dashboard."},{title:"Organize contatos e oportunidades",body:"Cadastre contatos com autorização, organize-os em listas e acompanhe cada etapa pelo CRM."},{title:"Converse e crie campanhas",body:"Use Templates, Mensagens e Campanhas para conversar com contatos que consentiram em receber comunicações."},{title:"Conecte seus canais",body:"Em Integrações, configure a Evolution API no servidor e acompanhe o status da conexão."}];
export function Shell({children}:{children:React.ReactNode}){
 const[open,setOpen]=useState(false);const[account,setAccount]=useState<Account|null>(null);const[billing,setBilling]=useState<Billing|null>(null);const[upgradeMessage,setUpgradeMessage]=useState("");const path=usePathname();const router=useRouter();
 const[termsRequired,setTermsRequired]=useState(false);const[termsChecked,setTermsChecked]=useState(false);const[termsBusy,setTermsBusy]=useState(false);const[tourStep,setTourStep]=useState<number|null>(null);
 useEffect(()=>{if(path==="/login")return;fetch("/api/auth/me").then(async response=>{if(!response.ok)throw new Error("Sessão expirada.");const data=await response.json();setAccount(data.user)}).catch(()=>window.location.replace("/login"))},[path]);
 useEffect(()=>{if(!account||path==="/login")return;fetch("/api/legal-consent",{cache:"no-store"}).then(response=>response.ok?response.json():Promise.reject()).then(data=>{if(!data.accepted){setTermsRequired(true);return}if(localStorage.getItem(`flowsend-tour-v1:${account.id}`)!=="done")setTourStep(0)}).catch(()=>{})},[account,path]);
 useEffect(()=>{if(path==="/login")return;const refresh=()=>fetch("/api/billing",{cache:"no-store"}).then(async response=>{if(response.ok){const data=await response.json();setBilling(data.subscription)}}).catch(()=>{});refresh();const timer=window.setInterval(refresh,30000);window.addEventListener("flowsend:billing-changed",refresh);return()=>{window.clearInterval(timer);window.removeEventListener("flowsend:billing-changed",refresh)}},[path]);
 useEffect(()=>{const onLimit=(event:Event)=>{const detail=(event as CustomEvent<{message?:string}>).detail;setUpgradeMessage(detail?.message||"Seu plano atingiu um limite.")};window.addEventListener("flowsend:plan-limit",onLimit);return()=>window.removeEventListener("flowsend:plan-limit",onLimit)},[]);
 async function logout(){await fetch("/api/auth/logout",{method:"POST"}).catch(()=>{});router.replace("/login")}
 async function acceptTerms(){setTermsBusy(true);try{const response=await fetch("/api/legal-consent",{method:"POST"});if(!response.ok)throw new Error();setTermsRequired(false);if(account&&localStorage.getItem(`flowsend-tour-v1:${account.id}`)!=="done")setTourStep(0)}catch{setUpgradeMessage("Não foi possível registrar o aceite. Confira sua conexão e tente novamente.")}finally{setTermsBusy(false)}}
 function finishTour(){if(account)localStorage.setItem(`flowsend-tour-v1:${account.id}`,"done");setTourStep(null)}
 if(path==="/login")return <>{children}</>;
 const initials=account?.name.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase()||"U";
 return <div className="app-shell"><Sidebar open={open} onClose={()=>setOpen(false)} account={account} onLogout={logout} billing={billing}/><main className="main"><header className="topbar"><button className="menu-button" onClick={()=>setOpen(true)} aria-label="Abrir menu"><Menu/></button><div className="breadcrumbs"><span>Workspace</span><b>/</b><strong>{titles[path]||"FlowSend"}</strong></div><div className="top-actions"><button className="search-trigger" onClick={()=>router.push("/contatos")}><Search size={15}/> <span>Buscar contatos, campanhas...</span><kbd><Command size={11}/> K</kbd></button><Link href="/planos" className="top-plan-badge"><Crown size={13}/> Plano {billing?.planName||"Starter"}</Link><button className="icon-button notification" aria-label="Notificações" onClick={()=>router.push("/mensagens")}><Bell size={18}/><i/></button><div className="top-divider"/><button className="top-account" onClick={logout} title="Sair"><span className="profile-avatar">{initials}</span><LogOut size={15}/></button></div></header><div className="page-wrap">{children}</div></main><UpgradeModal message={upgradeMessage} onClose={()=>setUpgradeMessage("")}/>
 {termsRequired&&<div className="modal-backdrop legal-backdrop"><section className="modal legal-modal" role="dialog" aria-modal="true" aria-labelledby="terms-heading"><div className="eyebrow"><ShieldCheck size={14}/> PRIMEIRO ACESSO · VERSÃO 2026-10-01</div><h2 id="terms-heading">Termos de Uso e Privacidade</h2><p>Antes de continuar, revise como o FlowSend trata sua conta e os dados que você cadastra.</p><div className="legal-copy"><h3>Uso do serviço</h3><p>O FlowSend organiza contatos, campanhas e conversas da sua operação. Você é responsável por cadastrar dados corretos, manter suas credenciais seguras e usar o serviço em conformidade com a legislação aplicável.</p><h3>Mensagens e contatos</h3><p>Envie mensagens somente a pessoas que autorizaram o contato. Respeite pedidos de saída e mantenha registros de consentimento. O workspace pode armazenar nome, telefone, empresa, histórico de conversas e preferências para prestar o serviço.</p><h3>Privacidade e integrações</h3><p>Os dados ficam no armazenamento configurado pelo administrador do workspace. Integrações externas, como Evolution API e provedores de IA, recebem apenas os dados necessários à ação solicitada. Não informe dados sensíveis em mensagens ou prompts.</p><h3>Disponibilidade e cobrança</h3><p>Os recursos podem depender de serviços externos e configuração do administrador. Planos e limites são exibidos no aplicativo; cobrança e pagamentos online só ficam ativos quando um provedor é configurado.</p><p>Esta versão apresenta as condições básicas de uso e privacidade do produto e pode ser atualizada pelo administrador.</p></div><label className="legal-check"><input type="checkbox" checked={termsChecked} onChange={event=>setTermsChecked(event.target.checked)}/> <span>Li e aceito os Termos de Uso e a Política de Privacidade.</span></label><div className="modal-actions"><button className="btn btn-primary" disabled={!termsChecked||termsBusy} onClick={acceptTerms}>{termsBusy?"Registrando…":<><Check size={15}/> Aceitar e continuar</>}</button></div></section></div>}
 {tourStep!==null&&!termsRequired&&<div className="modal-backdrop"><section className="modal tour-modal" role="dialog" aria-modal="true" aria-labelledby="tour-heading"><button className="modal-close" aria-label="Pular tutorial" onClick={finishTour}>×</button><div className="eyebrow"><Sparkles size={14}/> GUIA RÁPIDO · {tourStep+1} DE {tourSteps.length}</div><div className="wizard-progress"><i style={{width:`${(tourStep+1)*100/tourSteps.length}%`}}/></div><h2 id="tour-heading">{tourSteps[tourStep].title}</h2><p>{tourSteps[tourStep].body}</p><div className="modal-actions"><button className="btn btn-outline" onClick={finishTour}>Pular tutorial</button>{tourStep>0&&<button className="btn btn-outline" onClick={()=>setTourStep(tourStep-1)}><ArrowLeft size={14}/> Voltar</button>}<button className="btn btn-primary" onClick={()=>tourStep===tourSteps.length-1?finishTour():setTourStep(tourStep+1)}>{tourStep===tourSteps.length-1?"Concluir":"Próximo"} <ArrowRight size={14}/></button></div></section></div>}
 </div>
}
