import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {getCurrentUser,hashPassword} from "@/lib/auth/server";
import {readStore,updateStore} from "@/lib/storage/db";

const createSchema=z.object({name:z.string().trim().min(2).max(100),email:z.string().trim().email().max(254),password:z.string().min(10).max(200),role:z.enum(["admin","user"])});
const patchSchema=z.object({id:z.string().min(1),changes:z.object({name:z.string().trim().min(2).max(100).optional(),email:z.string().trim().email().max(254).optional(),password:z.string().min(10).max(200).optional(),role:z.enum(["admin","user"]).optional(),status:z.enum(["active","disabled"]).optional()}).refine(changes=>Object.keys(changes).length>0)});
const safe=(user:{id:string;name:string;email:string;role:"admin"|"user";status:"active"|"disabled";createdAt:string;lastLoginAt?:string})=>({id:user.id,name:user.name,email:user.email,role:user.role,status:user.status,createdAt:user.createdAt,lastLoginAt:user.lastLoginAt});
async function admin(request:NextRequest){const user=await getCurrentUser(request);if(!user)return {response:NextResponse.json({error:"Sessão expirada."},{status:401})};if(user.role!=="admin")return {response:NextResponse.json({error:"Apenas administradores podem gerenciar usuários."},{status:403})};return {user}}

export async function GET(request:NextRequest){const access=await admin(request);if(access.response)return access.response;return NextResponse.json((await readStore()).users.map(safe))}
export async function POST(request:NextRequest){const access=await admin(request);if(access.response)return access.response;try{const input=createSchema.parse(await request.json());const email=input.email.toLowerCase();const password=hashPassword(input.password);const user=await updateStore(store=>{if(store.users.some(row=>row.email===email))throw new Error("Já existe uma conta com este e-mail.");const row={id:crypto.randomUUID(),name:input.name,email,passwordHash:password.hash,passwordSalt:password.salt,role:input.role,status:"active" as const,createdAt:new Date().toISOString()};store.users.push(row);return safe(row)});return NextResponse.json(user,{status:201})}catch(error){return NextResponse.json({error:error instanceof z.ZodError?error.issues[0]?.message:error instanceof Error?error.message:"Não foi possível cadastrar usuário."},{status:error instanceof z.ZodError?400:409})}}
export async function PATCH(request:NextRequest){const access=await admin(request);if(access.response)return access.response;try{const {id,changes}=patchSchema.parse(await request.json());if(id===access.user.id)return NextResponse.json({error:"Para alterar seu próprio acesso, use outra conta administradora."},{status:409});const password=changes.password?hashPassword(changes.password):undefined;const updated=await updateStore(store=>{const target=store.users.find(row=>row.id===id);if(!target)throw new Error("Usuário não encontrado.");if(changes.email&&store.users.some(row=>row.id!==id&&row.email===changes.email!.toLowerCase()))throw new Error("Já existe uma conta com este e-mail.");const removesAdmin=target.role==="admin"&&target.status==="active"&&(changes.role==="user"||changes.status==="disabled");if(removesAdmin&&store.users.filter(row=>row.role==="admin"&&row.status==="active").length<=1)throw new Error("Mantenha ao menos um administrador ativo.");if(changes.name)target.name=changes.name;if(changes.email)target.email=changes.email.toLowerCase();if(changes.role)target.role=changes.role;if(changes.status)target.status=changes.status;if(password){target.passwordHash=password.hash;target.passwordSalt=password.salt}if(changes.status==="disabled"||password)store.sessions=store.sessions.filter(session=>session.userId!==id);return safe(target)});return NextResponse.json(updated)}catch(error){return NextResponse.json({error:error instanceof z.ZodError?error.issues[0]?.message:error instanceof Error?error.message:"Não foi possível atualizar usuário."},{status:error instanceof z.ZodError?400:409})}}
